export const pages = [
  {
    slug: "ansiedade-constante",
    title: "Ansiedade Constante: Como Organizar Seus Pensamentos",
    description: "Entenda a ansiedade constante e como organizar emoções para recuperar clareza mental.",
    h1: "Ansiedade Constante Não É Fraqueza",
    intro: "Sentir ansiedade todos os dias desgasta sua energia e sua confiança.",
    problem: "Quando a mente não para e o estado de alerta se torna o seu 'normal', você começa a duvidar de si mesmo e da sua capacidade de lidar com a vida.",
    solution: "Organizar as emoções através de técnicas estruturadas reduz a confusão mental, diminui o ruído interno e ajuda você a recuperar a direção e a paz.",
    related: ["ansiedade-e-medo-constante", "como-controlar-a-ansiedade"],
    cta: { title: "Quer organizar sua mente?", text: "Fale com nosso assistente para técnicas de clareza mental." }
  },
  {
    slug: "mente-acelerada",
    title: "Mente Acelerada: Como Reduzir Pensamentos Excessivos",
    description: "Descubra como organizar pensamentos acelerados e recuperar foco.",
    h1: "Pensamentos Acelerados Não São Falta de Controle",
    intro: "Sua mente não está quebrada. Está sobrecarregada por um excesso de processamento emocional.",
    problem: "O excesso de informação e a preocupação com o futuro geram um ruído mental ensurdecedor, impedindo o descanso e o foco no aqui e agora.",
    solution: "Criar uma estrutura mental sólida através de exercícios de ancoragem e organização reduz o ruído e aumenta a clareza de forma imediata.",
    related: ["ansiedade-antes-de-dormir", "como-controlar-a-ansiedade"],
    cta: { title: "Sua mente não para?", text: "O assistente pode guiar você em uma sessão de ancoragem." }
  },
  {
    slug: "sintomas-de-crise-de-ansiedade",
    title: "Sintomas de Crise de Ansiedade: o que acontece no corpo",
    description: "Conheça os sintomas de uma crise de ansiedade: taquicardia, falta de ar, tremores e como identificar o episódio.",
    h1: "Sintomas de Crise de Ansiedade",
    intro: "Uma crise de ansiedade provoca reações físicas e emocionais intensas que podem durar de minutos a horas.",
    problem: "A sensação de perda de controle e os sintomas físicos intensos, como falta de ar e taquicardia, fazem você acreditar que está em perigo real iminente.",
    solution: "Compreender que esses sintomas são uma resposta fisiológica de 'luta ou fuga' permite que você use técnicas de respiração para sinalizar segurança ao seu cérebro.",
    callout: { text: "🫁 Se está em crise agora: respire devagar. Inspire 4s, segure 4s, expire 6s.", bg: "rgba(59,130,246,0.1)", color: "var(--primary)" },
    sections: [
      { title: "Sintomas físicos", items: ["Taquicardia intensa", "Falta de ar ou hiperventilação", "Tremores e espasmos musculares", "Sudorese fria", "Formigamento nas mãos e rosto", "Náusea e desconforto gástrico", "Tontura e sensação de desmaio"] },
      { title: "Sintomas emocionais", items: ["Medo intenso de morrer ou perder o controle", "Sensação de irrealidade (desrealização)", "Desespero e urgência de fugir", "Sensação de loucura iminente"] }
    ],
    faq: [{ question: "Crise de ansiedade e ataque de pânico são a mesma coisa?", answer: "São muito similares, mas o ataque de pânico tende a ser mais intenso e abrupto." }],
    related: ["sintomas-de-ansiedade-no-corpo", "ansiedade-sintomas-fisicos"],
    cta: { title: "Em crise agora?", text: "Nosso assistente pode te guiar em exercícios de respiração." }
  },
  {
    slug: "sintomas-de-ansiedade-no-corpo",
    title: "Sintomas de Ansiedade no Corpo: como a ansiedade se manifesta fisicamente",
    description: "Entenda como a ansiedade afeta o corpo: tensão muscular, problemas digestivos, dores e outros sintomas somáticos.",
    h1: "Sintomas de Ansiedade no Corpo",
    intro: "A ansiedade não mora só na mente. Ela se instala no corpo e pode causar sintomas físicos reais e persistentes.",
    problem: "A somatização da ansiedade gera tensões, dores e desconfortos que muitas vezes são confundidos com doenças físicas graves, aumentando o ciclo de medo.",
    solution: "Identificar a origem emocional desses sintomas e aplicar técnicas de relaxamento progressivo ajuda o corpo a desativar o estado de alerta constante.",
    sections: [
      { title: "Sistema cardiovascular", items: ["Taquicardia e palpitações", "Pressão no peito"] },
      { title: "Sistema digestivo", items: ["Náusea e enjoo", "Refluxo e gastrite nervosa"] },
      { title: "Sistema muscular", items: ["Tensão no pescoço e ombros", "Mandíbula travada (bruxismo)"] }
    ],
    related: ["ansiedade-sintomas-fisicos", "taquicardia-e-ansiedade"],
    cta: { title: "Sentindo no corpo?", text: "Converse com nosso assistente para técnicas de relaxamento muscular." }
  },
  {
    slug: "ansiedade-sintomas-fisicos",
    title: "Ansiedade Sintomas Fisicos: os 10 sinais mais comuns",
    description: "Os 10 sintomas físicos mais comuns da ansiedade explicados pela ciência: taquicardia, tremores, sudorese e mais.",
    h1: "Ansiedade: Sintomas Físicos Mais Comuns",
    intro: "Quando a ansiedade ativa o sistema de luta ou fuga, o corpo responde com uma cascata de reações físicas.",
    problem: "Reações físicas automáticas como tremores, tontura e sudorese geram desconforto extremo e impedem a realização de tarefas simples do dia a dia.",
    solution: "Aprender a reconhecer esses 10 sinais como manifestações de estresse permite que você recupere o controle através da regulação do sistema nervoso.",
    sections: [
      { title: "Os 10 sinais mais comuns", items: ["Taquicardia", "Falta de ar", "Tremores", "Sudorese", "Formigamento", "Tensão muscular", "Náusea", "Tontura", "Dor de cabeça", "Insônia"] }
    ],
    related: ["ansiedade-sintomas-emocionais", "formigamento-e-ansiedade"],
    cta: { title: "Reconhece esses sintomas?", text: "Converse com nosso assistente para entender o que está sentindo." }
  },
  {
    slug: "ansiedade-sintomas-emocionais",
    title: "Ansiedade Sintomas Emocionais: como a mente é afetada",
    description: "Conheça os sintomas emocionais da ansiedade: preocupação excessiva, medo, irritabilidade, dificuldade de concentração.",
    h1: "Ansiedade: Sintomas Emocionais e Psicológicos",
    intro: "Além dos sintomas físicos, a ansiedade afeta profundamente o estado emocional e cognitivo.",
    problem: "A preocupação excessiva e o medo constante geram uma exaustão mental que impede o foco e afeta diretamente a qualidade dos seus relacionamentos e trabalho.",
    solution: "Práticas de mindfulness e reestruturação cognitiva ajudam a lidar com pensamentos intrusivos, reduzindo a carga emocional negativa.",
    related: ["ansiedade-e-medo-constante", "sensacao-de-morte-iminente"],
    cta: { title: "Pensamentos acelerados?", text: "Converse com nosso assistente para técnicas de organização mental." }
  },
  {
    slug: "taquicardia-e-ansiedade",
    title: "Taquicardia e Ansiedade: por que o coração acelera",
    description: "Entenda a relação entre taquicardia e ansiedade: por que o coração acelera, quando se preocupar e como aliviar.",
    h1: "Taquicardia e Ansiedade: O Coração Acelerado",
    intro: "O coração acelerado é o sintoma mais assustador da ansiedade — e também o mais comum.",
    problem: "A palpitação súbita no peito ativa imediatamente um medo de infarto, o que libera ainda mais adrenalina e piora o sintoma em um ciclo vicioso.",
    solution: "Normalizar a taquicardia como uma resposta de sobrevivência e praticar a respiração lenta sinaliza ao coração que ele pode retornar ao ritmo normal.",
    related: ["falta-de-ar-e-ansiedade", "crise-de-ansiedade-pode-matar"],
    cta: { title: "Coração acelerado agora?", text: "Nosso assistente pode guiar exercícios de respiração." }
  },
  {
    slug: "falta-de-ar-e-ansiedade",
    title: "Falta de Ar e Ansiedade: entenda a dispneia funcional",
    description: "Por que a ansiedade causa falta de ar, como diferenciar de problemas pulmonares e técnicas de respiração para alívio.",
    h1: "Falta de Ar e Ansiedade",
    intro: "A sensação de não conseguir respirar é uma das queixas mais frequentes nos pronto-socorros.",
    problem: "A hiperventilação gera uma falsa sensação de sufocamento, mesmo que seus pulmões estejam recebendo oxigênio suficiente, gerando pânico agudo.",
    solution: "Reequilibrar os níveis de CO2 através da respiração diafragmática interrompe a dispneia funcional e traz alívio imediato para os pulmões.",
    related: ["formigamento-e-ansiedade", "taquicardia-e-ansiedade"],
    cta: { title: "Dificuldade para respirar?", text: "Nosso assistente pode guiar exercícios de respiração em tempo real." }
  },
  {
    slug: "formigamento-e-ansiedade",
    title: "Formigamento e Ansiedade: por que o corpo formiga",
    description: "Entenda por que a ansiedade causa formigamento nas mãos, pés e rosto e como aliviar esse sintoma.",
    h1: "Formigamento e Ansiedade",
    intro: "O formigamento é um dos sintomas que mais assustam, pois muitas pessoas associam à AVC ou problemas neurológicos.",
    problem: "A vasoconstrição periférica causada pelo estresse reduz a circulação nas extremidades, gerando arrepios e formigamentos que alimentam o medo de doenças graves.",
    solution: "Corrigir a respiração e usar técnicas de grounding reconecta você com seu corpo e elimina a base fisiológica do formigamento ansioso.",
    related: ["falta-de-ar-e-ansiedade", "sintomas-de-ansiedade-no-corpo"],
    cta: { title: "Corpo formigando?", text: "Nosso assistente pode te guiar em exercícios de alívio." }
  },
  {
    slug: "quanto-tempo-dura-uma-crise-de-ansiedade",
    title: "Quanto Tempo Dura Uma Crise de Ansiedade? Duração e fases",
    description: "Saiba quanto tempo dura uma crise de ansiedade, quais são as fases do episódio e o que esperar.",
    h1: "Quanto Tempo Dura Uma Crise de Ansiedade?",
    intro: "A boa notícia é que as crises têm tempo limitado, mesmo que pareçam eternas no momento.",
    problem: "Sem saber quando o sofrimento vai acabar, a incerteza prolonga a sensação de desespero e impede você de aplicar estratégias de calma.",
    solution: "Mapear as fases da crise — pico e resolução — ajuda a aceitar o processo e permite que você espere os sintomas passarem com mais segurança.",
    related: ["o-que-fazer-em-uma-crise-de-ansiedade", "crise-de-ansiedade-pode-matar"],
    cta: { title: "Passando por uma crise agora?", text: "Nosso assistente pode te guiar em exercícios para reduzir a duração." }
  },
  {
    slug: "o-que-fazer-em-uma-crise-de-ansiedade",
    title: "O Que Fazer em Uma Crise de Ansiedade: guia prático",
    description: "Aprenda o que fazer durante uma crise de ansiedade: respiração, grounding, manobras vagais.",
    h1: "O Que Fazer em Uma Crise de Ansiedade: Guia Prático",
    intro: "Existem estratégias baseadas em evidências que podem encurtar a crise e reduzir o sofrimento.",
    problem: "No meio do furacão emocional, é difícil lembrar o que fazer, e o desespero de não saber como sair da crise só a intensifica.",
    solution: "Ter um roteiro estruturado de ações (Reconhecer, Respirar, Grounding) fornece o controle necessário para desativar a resposta de medo.",
    related: ["como-ajudar-alguem-em-crise-de-ansiedade", "quanto-tempo-dura-uma-crise-de-ansiedade"],
    cta: { title: "Precisa de apoio agora?", text: "Nosso assistente pode guiar exercícios de respiração em tempo real." }
  },
  {
    slug: "como-ajudar-alguem-em-crise-de-ansiedade",
    title: "Como Ajudar Alguém em Crise de Ansiedade: guia para acompanhantes",
    description: "Aprenda como ajudar durante uma crise de ansiedade: o que dizer, o que evitar e técnicas de apoio.",
    h1: "Como Ajudar Alguém em Crise de Ansiedade",
    intro: "Sua presença calma e acolhedora pode fazer toda a diferença durante uma crise.",
    problem: "Ver alguém que amamos em desespero gera impotência, e reagir de forma errada (como pedir 'calma') pode acabar piorando a situação.",
    solution: "Seguir um protocolo de validação e guia respiratório permite que você seja a 'âncora' que a pessoa precisa para retornar ao equilíbrio.",
    related: ["o-que-fazer-em-uma-crise-de-ansiedade", "crise-de-ansiedade-pode-matar"],
    cta: { title: "Quer orientação?", text: "Nosso assistente pode orientar sobre técnicas de apoio." }
  },
  {
    slug: "crise-de-ansiedade-pode-matar",
    title: "Crise de Ansiedade Pode Matar? A verdade médica",
    description: "Crise de ansiedade pode matar? Entenda a verdade médica sobre o risco das crises.",
    h1: "Crise de Ansiedade Pode Matar?",
    intro: "Este é um dos maiores medos de quem vive com ansiedade.",
    problem: "A convicção de que seu corpo vai falhar sob a pressão da ansiedade gera um trauma que faz você viver com medo de ter uma nova crise.",
    solution: "Compreender a fisiologia da ansiedade desmistifica o medo da morte e permite que você encare as crises como alarmes falsos, não como ameaças fatais.",
    related: ["sensacao-de-morte-iminente", "quanto-tempo-dura-uma-crise-de-ansiedade"],
    cta: { title: "Está com medo agora?", text: "Converse com nosso assistente para acolhimento." }
  },
  {
    slug: "ansiedade-generalizada",
    title: "Ansiedade Generalizada: o que é, sintomas e como tratar",
    description: "Saiba o que é ansiedade generalizada, seus sintomas, causas e tratamentos.",
    h1: "Ansiedade Generalizada: O Que É e Como Tratar",
    intro: "A ansiedade generalizada é uma preocupação excessiva e persistente sobre diversos aspectos da vida.",
    problem: "Viver em 'estado de alerta' por meses seguidos esgota sua energia vital, destrói seu sono e impede que você aproveite o momento presente.",
    solution: "Tratamentos baseados em TCC e regulação de neurotransmissores ajudam a recalibrar o sistema de alarme do cérebro para níveis saudáveis.",
    related: ["transtorno-do-panico", "ansiedade-social"],
    cta: { title: "Precisa de acolhimento?", text: "Nosso assistente pode ajudar a organizar pensamentos." }
  },
  {
    slug: "ansiedade-social",
    title: "Ansiedade Social (Fobia Social): sintomas e tratamento",
    description: "Entenda a ansiedade social: medo intenso de julgamento, sintomas, causas e tratamento com TCC.",
    h1: "Ansiedade Social: Muito Mais do Que Timidez",
    intro: "A ansiedade social vai além da timidez. É um medo intenso de ser julgado ou humilhado por outros.",
    problem: "O medo da avaliação negativa faz você evitar oportunidades, se isolar e sentir uma autocrítica devastadora após cada interação social.",
    solution: "A exposição gradual e o desafio de pensamentos perfeccionistas permitem que você recupere sua liberdade de interagir socialmente.",
    related: ["ansiedade-generalizada", "terapias-para-ansiedade"],
    cta: { title: "Se identifica?", text: "Converse em um espaço seguro e sem julgamento." }
  },
  {
    slug: "ansiedade-de-separacao",
    title: "Ansiedade de Separação: sintomas em crianças e adultos",
    description: "Entenda a ansiedade de separação em crianças e adultos: sintomas, causas e quando buscar tratamento.",
    h1: "Ansiedade de Separação: Em Crianças e Adultos",
    intro: "Medo intenso e desproporcional de se afastar de figuras de apego.",
    problem: "A dependência emocional extrema gera angústia constante tanto em quem sente quanto em quem é o objeto do apego, limitando a autonomia de ambos.",
    solution: "Fortalecer a segurança interna e trabalhar os vínculos de apego ajuda a reduzir o pânico da separação e promove relacionamentos mais saudáveis.",
    related: ["ansiedade-generalizada", "ansiedade-e-medo-constante"],
    cta: { title: "Precisa de apoio?", text: "Converse para entender melhor seus padrões emocionais." }
  },
  {
    slug: "transtorno-do-panico",
    title: "Transtorno do Pânico: sintomas, crises e tratamento",
    description: "Tudo sobre transtorno do pânico: ataques recorrentes, medo de novas crises e tratamento.",
    h1: "Transtorno do Pânico: Quando o Medo Domina",
    intro: "Caracterizado por ataques recorrentes e inesperados de medo intenso com sintomas físicos severos.",
    problem: "O 'medo de ter medo' faz você limitar sua vida geográfica e social, vivendo em função de evitar uma próxima crise que parece inevitável.",
    solution: "Técnicas de exposição interoceptiva ensinam seu cérebro que as sensações de pânico são seguras, quebrando o ciclo de evitação.",
    related: ["diferenca-entre-ansiedade-e-panico", "sensacao-de-morte-iminente"],
    cta: { title: "Precisa de acolhimento?", text: "Nosso assistente pode ajudar durante momentos difíceis." }
  },
  {
    slug: "diferenca-entre-ansiedade-e-panico",
    title: "Diferença entre Ansiedade e Pânico: como distinguir",
    description: "Entenda a diferença entre ansiedade e pânico: critérios, sintomas, duração e abordagens.",
    h1: "Diferença entre Ansiedade e Pânico",
    intro: "Embora compartilhem sintomas, são condições distintas com diferenças importantes.",
    problem: "Confundir um estado de ansiedade crônica com um ataque de pânico pode levar a estratégias erradas de manejo e aumento da frustração.",
    solution: "Saber distinguir o início gradual da ansiedade vs. o pico abrupto do pânico permite que você aplique a ferramenta certa para cada momento.",
    related: ["transtorno-do-panico", "ansiedade-generalizada"],
    cta: { title: "Quer entender o que sente?", text: "Converse para explorar seus sintomas de forma segura." }
  },
  {
    slug: "remedios-para-ansiedade",
    title: "Remédios para Ansiedade: classes, indicações e cuidados",
    description: "Guia sobre remédios para ansiedade: ISRS, benzodiazepínicos e prescrição médica.",
    h1: "Remédios para Ansiedade: Guia Completo",
    intro: "O tratamento farmacológico deve sempre ser combinado com psicoterapia e mudanças de hábitos.",
    problem: "O medo de efeitos colaterais ou da dependência química muitas vezes impede pessoas de buscarem o suporte biológico necessário para sua recuperação.",
    solution: "Informação clara sobre como as classes de medicamentos (ISRS vs Benzodiazepínicos) atuam permite um tratamento consciente e seguro sob supervisão médica.",
    callout: { text: "⚠️ NUNCA se automedique. Todos os medicamentos exigem prescrição médica.", bg: "rgba(239,68,68,0.1)", color: "#ef4444" },
    related: ["antidepressivo-para-ansiedade", "ansiolitico-o-que-e"],
    cta: { title: "Quer entender o que sente?", text: "Converse antes da sua consulta médica." }
  },
  {
    slug: "antidepressivo-para-ansiedade",
    title: "Antidepressivo para Ansiedade: como funciona",
    description: "Como antidepressivos tratam ansiedade, por que funcionam e efeitos colaterais.",
    h1: "Antidepressivo para Ansiedade: Entenda o Tratamento",
    intro: "Os mesmos neurotransmissores da depressão — especialmente serotonina — também regulam a ansiedade.",
    problem: "A demora para o início do efeito dos antidepressivos gera ansiedade adicional e risco de desistência do tratamento nas primeiras semanas.",
    solution: "Compreender o tempo de latência de 2 a 6 semanas ajuda você a persistir no tratamento até que a regulação emocional se estabilize.",
    related: ["remedios-para-ansiedade", "ansiolitico-o-que-e"],
    cta: { title: "Dúvidas sobre medicação?", text: "Nosso assistente pode ajudar a preparar perguntas para o médico." }
  },
  {
    slug: "ansiolitico-o-que-e",
    title: "Ansiolítico: O Que É, Como Funciona e Riscos",
    description: "O que são ansiolíticos, como atuam no cérebro, indicações e riscos de dependência.",
    h1: "Ansiolítico: O Que É e Como Funciona",
    intro: "Ansiolítico é qualquer medicamento que reduz a ansiedade de forma rápida.",
    problem: "O uso indiscriminado de ansiolíticos para 'apagar' o mal-estar pode levar à dependência severa e mascarar as causas emocionais da ansiedade.",
    solution: "Usar ansiolíticos apenas como suporte pontual, integrando-os a um plano terapêutico maior, garante alívio sem comprometer a saúde a longo prazo.",
    related: ["antidepressivo-para-ansiedade", "remedios-para-ansiedade"],
    cta: { title: "Quer entender suas opções?", text: "Nosso assistente pode auxiliar na organização de dúvidas." }
  },
  {
    slug: "cha-para-ansiedade",
    title: "Chá para Ansiedade: opções naturais que podem ajudar",
    description: "Melhores chás para ansiedade: camomila, passiflora, erva-cidreira e valeriana.",
    h1: "Chá para Ansiedade: Opções Naturais",
    intro: "Algumas ervas possuem evidência científica moderada para auxiliar no manejo da ansiedade leve.",
    problem: "Acreditar que apenas recursos naturais podem resolver transtornos graves pode atrasar o tratamento necessário, enquanto ignorá-los desperdiça aliados úteis.",
    solution: "Integrar chás com propriedades comprovadas (como Passiflora e Camomila) na sua rotina cria um ambiente de suporte natural para a calma mental.",
    related: ["tratamento-para-ansiedade", "como-controlar-a-ansiedade"],
    cta: { title: "Quer mais dicas?", text: "Nosso assistente pode sugerir técnicas complementares." }
  },
  {
    slug: "tratamento-para-ansiedade",
    title: "Tratamento para Ansiedade: guia completo",
    description: "Todas as opções de tratamento: terapia, medicação, exercício e mudanças de vida.",
    h1: "Tratamento para Ansiedade: Guia Completo",
    intro: "O tratamento é multifacetado e deve ser individualizado.",
    problem: "Tentar tratar a ansiedade apenas com um recurso (só remédio ou só chá) costuma ser insuficiente, levando a recaídas frequentes.",
    solution: "A abordagem multidisciplinar — unindo terapia, biologia e estilo de vida — é o caminho mais sólido para uma remissão sustentada dos sintomas.",
    related: ["terapias-para-ansiedade", "remedios-para-ansiedade"],
    cta: { title: "Quer dar o primeiro passo?", text: "Converse para identificar padrões e aprender técnicas." }
  },
  {
    slug: "terapia-para-ansiedade",
    title: "Terapia para Ansiedade: tipos e qual escolher",
    description: "Terapias mais eficazes para ansiedade: TCC, ACT, EMDR e psicodinâmica.",
    h1: "Terapia para Ansiedade: Qual Escolher?",
    intro: "A psicoterapia é primeira linha no tratamento. Existem diversas abordagens.",
    problem: "A infinidade de abordagens terapêuticas gera confusão, e escolher uma que não se adapta ao seu perfil pode desmotivar sua busca por ajuda.",
    solution: "Entender os focos de cada terapia (como o foco prático da TCC ou o emocional da ACT) ajuda você a encontrar o suporte que mais ressoa com sua dor.",
    related: ["tratamento-para-ansiedade", "como-controlar-a-ansiedade"],
    cta: { title: "Quer começar?", text: "Nosso assistente pode ajudar a praticar técnicas de TCC." }
  },
  {
    slug: "cid-ansiedade",
    title: "CID Ansiedade: código, classificação e significado",
    description: "Códigos CID da ansiedade: F41.0, F41.1, F40.1 e como a classificação funciona.",
    h1: "CID da Ansiedade: Códigos e Classificação",
    intro: "A CID é o sistema usado mundialmente para codificar condições de saúde.",
    problem: "Receber um código alfanumérico em um laudo médico sem explicação pode gerar medo de um diagnóstico 'permanente' ou incompreensível.",
    solution: "Traduzir os códigos CID para nomes e significados clínicos claros ajuda você a entender seu diagnóstico e a se comunicar melhor com seus médicos.",
    related: ["diagnostico-de-ansiedade", "criterios-para-transtorno-de-ansiedade"],
    cta: { title: "Quer entender seu caso?", text: "Nosso assistente ajuda a organizar informações para sua consulta." }
  },
  {
    slug: "diagnostico-de-ansiedade",
    title: "Diagnóstico de Ansiedade: como é feito e por quem",
    description: "Como é feito o diagnóstico: entrevista clínica, DSM-5 e profissionais indicados.",
    h1: "Diagnóstico de Ansiedade: Como É Feito",
    intro: "O diagnóstico é essencialmente clínico — baseado na história e observação do profissional.",
    problem: "Muitas pessoas sofrem por anos sem diagnóstico por medo do estigma ou por não saberem a qual profissional recorrer primeiro.",
    solution: "Um diagnóstico feito por psiquiatra ou psicólogo qualificado é o marco inicial da sua liberdade, permitindo um plano de ação preciso.",
    related: ["cid-ansiedade", "teste-de-ansiedade-online"],
    cta: { title: "Quer se preparar?", text: "Nosso assistente ajuda a mapear seus sintomas." }
  },
  {
    slug: "teste-de-ansiedade-online",
    title: "Teste de Ansiedade Online: rastreio GAD-7",
    description: "Teste de rastreio baseado na escala GAD-7. Não substitui avaliação profissional.",
    h1: "Teste de Ansiedade Online (Rastreio)",
    intro: "A escala GAD-7 é um instrumento validado cientificamente usado internacionalmente.",
    problem: "A dúvida sobre o nível da sua ansiedade gera insegurança. 'Será que o que sinto é normal ou preciso de ajuda profissional?'",
    solution: "Usar uma escala validada como o GAD-7 fornece um indicador objetivo que pode ser o incentivo necessário para buscar apoio especializado.",
    callout: { text: "⚠️ Este é um instrumento de rastreio educacional. NÃO constitui diagnóstico.", bg: "rgba(239,68,68,0.1)", color: "#ef4444" },
    related: ["diagnostico-de-ansiedade", "criterios-para-transtorno-de-ansiedade"],
    cta: { title: "Quer conversar sobre os resultados?", text: "Nosso assistente ajuda a entender os sinais." }
  },
  {
    slug: "criterios-para-transtorno-de-ansiedade",
    title: "Critérios para Transtorno de Ansiedade: DSM-5 e CID-11",
    description: "Critérios diagnósticos para TAG, pânico, fobia social e mais.",
    h1: "Critérios para Transtorno de Ansiedade",
    intro: "Diretrizes usadas por profissionais para identificar transtornos de forma padronizada.",
    problem: "Sintomas dispersos e confusos dificultam a percepção de que existe um transtorno tratável por trás do seu sofrimento constante.",
    solution: "Conhecer os critérios clínicos do DSM-5 ajuda você a nomear sua dor e a validar sua necessidade de tratamento específico.",
    related: ["cid-ansiedade", "diagnostico-de-ansiedade"],
    cta: { title: "Quer entender seus sintomas?", text: "Nosso assistente ajuda a mapear o que sente." }
  },
  {
    slug: "ansiedade-e-medo-constante",
    title: "Ansiedade e Medo Constante: por que acontece e como lidar",
    description: "Por que a ansiedade causa medo constante e como quebrar o ciclo de apreensão.",
    h1: "Ansiedade e Medo Constante: Por Que Isso Acontece",
    intro: "A sensação permanente de ameaça é uma das marcas mais dolorosas da ansiedade crônica.",
    problem: "Viver em hipervigilância, esperando o 'próximo desastre', impede o relaxamento e torna qualquer atividade cotidiana um fardo emocional.",
    solution: "Técnicas de teste de realidade e rebaixamento do sistema de alarme ajudam o cérebro a reconhecer que, no aqui e agora, você está seguro.",
    related: ["sensacao-de-morte-iminente", "ansiedade-sintomas-emocionais"],
    cta: { title: "Vivendo com medo?", text: "Converse para aprender técnicas de regulação emocional." }
  },
  {
    slug: "sensacao-de-morte-iminente",
    title: "Sensação de Morte Iminente: por que ansiedade causa esse medo",
    description: "Entenda a sensação de morte iminente na ansiedade: por que acontece e como lidar.",
    h1: "Sensação de Morte Iminente e Ansiedade",
    intro: "A sensação de que você vai morrer agora é um dos sintomas mais aterrorizantes da ansiedade.",
    problem: "O choque fisiológico da adrenalina é tão forte que a mente racional é silenciada pelo pânico agudo de um fim iminente.",
    solution: "Entender que essa sensação é apenas um 'erro de software' da amígdala cerebral permite que você atravesse o momento sem pânico adicional.",
    related: ["crise-de-ansiedade-pode-matar", "ansiedade-e-medo-constante"],
    cta: { title: "Está com medo agora?", text: "Nosso assistente pode guiar sua respiração." }
  },
  {
    slug: "ansiedade-antes-de-dormir",
    title: "Ansiedade Antes de Dormir: por que piora à noite",
    description: "Por que a ansiedade piora antes de dormir e técnicas para relaxar à noite.",
    h1: "Ansiedade Antes de Dormir: Por Que Piora à Noite",
    intro: "Você deita na cama e a mente dispara. O silêncio da noite vira o palco para as suas maiores preocupações.",
    problem: "A falta de estímulos externos à noite deixa o caminho livre para a ruminação, criando um ciclo de insônia que piora a ansiedade do dia seguinte.",
    solution: "Criar uma higiene do sono rigorosa e praticar o 'Body Scan' descarrega a tensão do corpo e prepara a mente para o descanso real.",
    related: ["acordar-com-ansiedade", "como-controlar-a-ansiedade"],
    cta: { title: "Não consegue dormir?", text: "Nosso assistente pode guiar seu relaxamento." }
  },
  {
    slug: "acordar-com-ansiedade",
    title: "Acordar com Ansiedade: por que acontece pela manhã",
    description: "Por que você acorda com ansiedade, o pico matinal de cortisol e como começar o dia.",
    h1: "Acordar com Ansiedade: Por Que Acontece",
    intro: "Abrir os olhos e já sentir o coração acelerado. A ansiedade matinal tem bases fisiológicas claras.",
    problem: "O pico natural de cortisol matinal é interpretado pelo cérebro ansioso como um sinal de perigo, fazendo o dia começar com um peso emocional enorme.",
    solution: "Rotinas matinais de baixo estímulo e respiração consciente ajudam a queimar o cortisol excedente e iniciam o dia com mais equilíbrio.",
    related: ["ansiedade-antes-de-dormir", "ansiedade-e-cansaco"],
    cta: { title: "Manhã difícil?", text: "Comece o dia com nosso assistente." }
  },
  {
    slug: "ansiedade-e-cansaco",
    title: "Ansiedade e Cansaço: por que a ansiedade esgota",
    description: "Relação entre ansiedade e cansaço extremo: por que a fadiga é um sintoma comum.",
    h1: "Ansiedade e Cansaço: A Exaustão Invisível",
    intro: "Você dorme, mas acorda cansado. A ansiedade consome uma quantidade imensa de energia vital.",
    problem: "O estado de alerta constante e a tensão muscular persistente funcionam como uma 'maratona mental' que drena suas reservas de energia.",
    solution: "Aprender a alternar estados de alerta com momentos de recuperação real permite que seu corpo saia do modo de sobrevivência e recupere o vigor.",
    related: ["acordar-com-ansiedade", "ansiedade-e-problemas-gastricos"],
    cta: { title: "Esgotado emocionalmente?", text: "Nosso assistente pode ajudar com descanso mental." }
  },
  {
    slug: "ansiedade-e-problemas-gastricos",
    title: "Ansiedade e Problemas Gástricos: eixo intestino-cérebro",
    description: "Como ansiedade causa náuseas, dores de estômago e problemas intestinais.",
    h1: "Ansiedade e Problemas Gástricos: O Eixo Intestino-Cérebro",
    intro: "O intestino é considerado nosso segundo cérebro e reage instantaneamente aos nossos estados emocionais.",
    problem: "Dores de estômago e enjoos constantes dificultam a alimentação e geram uma preocupação adicional com a saúde física, piorando o quadro geral.",
    solution: "Técnicas de respiração diafragmática massageiam o nervo vago e ajudam a acalmar o sistema digestivo sensibilizado pela ansiedade.",
    related: ["sintomas-de-ansiedade-no-corpo", "ansiedade-e-cansaco"],
    cta: { title: "Problemas digestivos?", text: "Converse para entender a relação com o emocional." }
  },
  {
    slug: "sintomas-de-ansiedade",
    title: "Sintomas de Ansiedade: sinais físicos e emocionais explicados",
    description: "Entenda os principais sintomas de ansiedade, sinais físicos no corpo e quando procurar ajuda.",
    h1: "Sintomas de Ansiedade: Como o Corpo e a Mente Reagem",
    intro: "A ansiedade pode se manifestar de forma física e emocional, muitas vezes de maneira confusa.",
    problem: "Não saber se o que você sente é ansiedade ou um problema físico gera uma busca incessante por respostas e um aumento do nível de estresse.",
    solution: "Mapear seus sinais físicos e emocionais de forma estruturada traz a clareza necessária para iniciar o tratamento correto e recuperar a paz.",
    related: ["sintomas-de-ansiedade-no-corpo", "ansiedade-sintomas-fisicos"],
    cta: { title: "Precisa conversar?", text: "Nosso assistente pode ajudar a mapear seus sinais." }
  },
  {
    slug: "crise-de-ansiedade",
    title: "Crise de Ansiedade: sintomas, causas e o que fazer",
    description: "Entenda os sintomas de uma crise de ansiedade e como agir em momentos de pico emocional.",
    h1: "Crise de Ansiedade: O Que Acontece no Corpo",
    intro: "A crise de ansiedade é um episódio intenso de medo que exige estratégias rápidas de manejo.",
    problem: "A natureza avassaladora da crise paralisa sua capacidade de pensar racionalmente, deixando você à mercê de sensações físicas assustadoras.",
    solution: "Ferramentas práticas de regulação emocional e respiração servem como um 'freio de mão' para desativar o pico da crise e trazer você de volta.",
    related: ["quanto-tempo-dura-uma-crise-de-ansiedade", "o-que-fazer-em-uma-crise-de-ansiedade"],
    cta: { title: "Está passando por isso?", text: "Nosso assistente pode guiar seu suporte agora." }
  },
  {
    slug: "transtorno-de-ansiedade-generalizada",
    title: "TAG - Transtorno de Ansiedade Generalizada: o que é e tratamento",
    description: "Saiba o que é o TAG, como identificar a preocupação excessiva e tratamentos eficazes.",
    h1: "Transtorno de Ansiedade Generalizada (TAG)",
    intro: "O TAG é caracterizado por preocupação persistente sobre diversos aspectos da vida cotidiana.",
    problem: "A incapacidade de 'desligar' a mente das preocupações futuras impede você de viver o presente e gera um sofrimento mental crônico.",
    solution: "A reestruturação cognitiva da TCC e o suporte biológico permitem que você aprenda a tolerar a incerteza e reduza o volume das preocupações.",
    related: ["ansiedade-generalizada", "criterios-para-transtorno-de-ansiedade"],
    cta: { title: "Preocupado o tempo todo?", text: "O assistente pode ajudar a organizar sua mente." }
  },
  {
    slug: "remedio-para-ansiedade",
    title: "Remédio para Ansiedade: quais existem e quando são indicados",
    description: "Classes de medicamentos para ansiedade e a importância crucial da prescrição médica.",
    h1: "Remédio para Ansiedade: Informações Importantes",
    intro: "O tratamento medicamentoso ajuda a regular neurotransmissores essenciais para a calma.",
    problem: "O estigma sobre o uso de medicação psiquiátrica ou a tentativa de automedicação podem piorar severamente o quadro de ansiedade.",
    solution: "Conhecer as classes de remédios e sua função biológica correta traz segurança para o paciente e otimiza a eficácia do tratamento médico.",
    callout: { text: "⚠️ Medicamentos devem ser prescritos exclusivamente por um médico psiquiatra.", bg: "rgba(239,68,68,0.1)", color: "#ef4444" },
    related: ["remedios-para-ansiedade", "tratamento-para-ansiedade"],
    cta: { title: "Quer entender as opções?", text: "Nosso assistente ajuda a identificar padrões." }
  },
  {
    slug: "como-controlar-a-ansiedade",
    title: "Como Controlar a Ansiedade: técnicas e estratégias eficazes",
    description: "Métodos práticos para controlar a ansiedade: mudanças de hábito e técnicas de respiração.",
    h1: "Como Controlar a Ansiedade de Forma Prática",
    intro: "Gerenciar a ansiedade requer persistência e as estratégias certas para acalmar a mente.",
    problem: "Tentar controlar a ansiedade apenas pela 'força de vontade' geralmente falha, gerando mais frustração e sensação de incapacidade.",
    solution: "Aplicar métodos baseados em fisiologia (respiração) e ciência comportamental fornece as ferramentas reais para a gestão emocional diária.",
    related: ["tratamento-para-ansiedade", "terapia-para-ansiedade"],
    cta: { title: "Quer praticar agora?", text: "Nosso assistente pode conduzir sessões de mindfulness." }
  },
  {
    slug: "ansiedade",
    title: "Ansiedade: Sintomas, Causas, Tipos e Formas de Tratamento",
    description: "Guia completo sobre ansiedade: sintomas, crises, tratamentos e ajuda profissional.",
    h1: "Ansiedade: Guia Completo sobre Sintomas e Tratamento",
    intro: "A ansiedade é uma resposta natural, mas em excesso pode se tornar um transtorno que exige cuidado.",
    problem: "A falta de informação organizada faz com que muitas pessoas sofram sozinhas, sem entender que seu problema tem nome e tratamento eficaz.",
    solution: "Este guia pilar centraliza o conhecimento necessário para você entender seu quadro, identificar sintomas e saber onde buscar ajuda profissional confiável.",
    related: ["sintomas-de-ansiedade", "crise-de-ansiedade", "tratamento-para-ansiedade"],
    cta: { title: "Precisa de acolhimento?", text: "Fale com nosso assistente virtual para suporte imediato." }
  }
];
